name: CI

on:
  push:
    branches: ["master"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
      - id: build-and-deploy
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          cname: formatter.djstormdrain.com
          username: "hpopp"
          reponame: "tracklist-formatter"
          token: ${{ secrets.GITHUB_TOKEN }}
